// components/Icon.tsx

import {
    Home,
    ShoppingBag,
    ShoppingCart,
    Store,
    User,
    Users,
    UserPlus,
    UserCheck,
    Settings,
    Search,
    Heart,
    Star,
    MapPin,
    Phone,
    Mail,
    Menu,
    CircleHelp,
    Info,
    Bell,
    Calendar,
    Clock,
    Check,
    X,
    Plus,
    Minus,
    ChevronDown,
    ChevronUp,
    ChevronLeft,
    ChevronRight,
    ArrowRight,
    ArrowLeft,
    ArrowUp,
    ArrowDown,
    ExternalLink,
    Link,
    Share2,
    Send,
    Download,
    Upload,
    Eye,
    EyeOff,
    Lock,
    Unlock,
    LogIn,
    LogOut,
    Key,
    Shield,
    ShieldCheck,
    CreditCard,
    Wallet,
    Banknote,
    Receipt,
    Tag,
    Tags,
    Package,
    Truck,
    Boxes,
    CircleDollarSign,
    Percent,
    BadgeDollarSign,
    Gift,
    Camera,
    Image,
    Video,
    File,
    FileText,
    Folder,
    FolderOpen,
    Pencil,
    Trash2,
    Copy,
    Save,
    MoreHorizontal,
    MoreVertical,
    Filter,
    SlidersHorizontal,
    List,
    Grid,
    LayoutDashboard,
    BarChart3,
    PieChart,
    TrendingUp,
    TrendingDown,
    Globe,
    Building,
    Briefcase,
    Map,
    Navigation,
    MessageCircle,
    MessagesSquare,
    Headphones,
    HelpCircle,
    CheckCircle,
    XCircle,
    AlertCircle,
    AlertTriangle,
    type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
    home: Home,
    shoppingBag: ShoppingBag,
    shoppingCart: ShoppingCart,
    store: Store,
    user: User,
    users: Users,
    userPlus: UserPlus,
    userCheck: UserCheck,
    settings: Settings,
    search: Search,
    heart: Heart,
    star: Star,
    mapPin: MapPin,
    phone: Phone,
    mail: Mail,
    menu: Menu,
    circleHelp: CircleHelp,
    info: Info,
    bell: Bell,
    calendar: Calendar,
    clock: Clock,
    check: Check,
    x: X,
    plus: Plus,
    minus: Minus,
    chevronDown: ChevronDown,
    chevronUp: ChevronUp,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    arrowRight: ArrowRight,
    arrowLeft: ArrowLeft,
    arrowUp: ArrowUp,
    arrowDown: ArrowDown,
    externalLink: ExternalLink,
    link: Link,
    share: Share2,
    send: Send,
    download: Download,
    upload: Upload,
    eye: Eye,
    eyeOff: EyeOff,
    lock: Lock,
    unlock: Unlock,
    login: LogIn,
    logout: LogOut,
    key: Key,
    shield: Shield,
    shieldCheck: ShieldCheck,
    creditCard: CreditCard,
    wallet: Wallet,
    banknote: Banknote,
    receipt: Receipt,
    tag: Tag,
    tags: Tags,
    package: Package,
    truck: Truck,
    boxes: Boxes,
    dollar: CircleDollarSign,
    percent: Percent,
    discount: BadgeDollarSign,
    gift: Gift,
    camera: Camera,
    image: Image,
    video: Video,
    file: File,
    fileText: FileText,
    folder: Folder,
    folderOpen: FolderOpen,
    edit: Pencil,
    delete: Trash2,
    copy: Copy,
    save: Save,
    moreHorizontal: MoreHorizontal,
    moreVertical: MoreVertical,
    filter: Filter,
    sliders: SlidersHorizontal,
    list: List,
    grid: Grid,
    dashboard: LayoutDashboard,
    barChart: BarChart3,
    pieChart: PieChart,
    trendingUp: TrendingUp,
    trendingDown: TrendingDown,
    globe: Globe,
    building: Building,
    briefcase: Briefcase,
    map: Map,
    navigation: Navigation,
    message: MessageCircle,
    messages: MessagesSquare,
    headphones: Headphones,
    help: HelpCircle,
    success: CheckCircle,
    error: XCircle,
    alert: AlertCircle,
    warning: AlertTriangle,
};

interface IconProps {
    name: string;
    className?: string;
}

export default function IconComponent({
    name,
    className,
}: IconProps) {
    const IconComponent = iconMap[name] ?? CircleHelp;

    return (
        <IconComponent
            className={className}
        />
    );
}

const iconsName = [
    "home",
    "shoppingBag",
    "shoppingCart",
    "store",
    "user",
    "users",
    "userPlus",
    "userCheck",
    "settings",
    "search",
    "heart",
    "star",
    "mapPin",
    "phone",
    "mail",
    "menu",
    "circleHelp",
    "info",
    "bell",
    "calendar",
    "clock",
    "check",
    "x",
    "plus",
    "minus",
    "chevronDown",
    "chevronUp",
    "chevronLeft",
    "chevronRight",
    "arrowRight",
    "arrowLeft",
    "arrowUp",
    "arrowDown",
    "externalLink",
    "link",
    "share",
    "send",
    "download",
    "upload",
    "eye",
    "eyeOff",
    "lock",
    "unlock",
    "login",
    "logout",
    "key",
    "shield",
    "shieldCheck",
    "creditCard",
    "wallet",
    "banknote",
    "receipt",
    "tag",
    "tags",
    "package",
    "truck",
    "boxes",
    "dollar",
    "percent",
    "discount",
    "gift",
    "camera",
    "image",
    "video",
    "file",
    "fileText",
    "folder",
    "folderOpen",
    "edit",
    "delete",
    "copy",
    "save",
    "moreHorizontal",
    "moreVertical",
    "filter",
    "sliders",
    "list",
    "grid",
    "dashboard",
    "barChart",
    "pieChart",
    "trendingUp",
    "trendingDown",
    "globe",
    "building",
    "briefcase",
    "map",
    "navigation",
    "message",
    "messages",
    "headphones",
    "help",
    "success",
    "error",
    "alert",
    "warning"
]

